# SITE CONFIGURATION
baseurl: ""
url: "https://haramlog.github.io/"

# THEME-SPECIFIC CONFIGURATION
title: Haram_log                                  # site's title
description: "leeharam"      # used by search engines
avatar: assets/img/ppap.png                       # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Haram_log of leeharam # Change Blog header text
header_feature_image: assets/img/pexels/mint.jpeg
footer_text: >
  개발자&nbsp; <strong>이하람</strong><br>경로&nbsp; <strong>haramlog.github.io</strong><br><br>CC BY-NC-SA 2.0 KR<br>All of posts which in this site can't use to profit.<br>Copyright © leeeharam All rights reserved.

# Blog
excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 6
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
